config/routes.rb
Rails.application.routes.draw do
 
  resources :users
  resources :urls, only: [:create]
  
  root 'static_pages#webhooks'
  match '/webhooks', to: 'static_pages#webhooks', via: 'get'

  match '/signin',   to: 'users#new',             via: 'get'
  match '/signout',  to: 'users#destroy',         via: :delete

end

app/models/url.rb
class Url
  include Enumerable

  attr_accessor :urls

  def initialize(key)
    @urls = Utils::get_webhook_urls(key).uniq 
    return @urls
  end

  def new(key)
  end

  def each(&block)
    @urls.each(&block)
  end

  def <<(url)
    @urls << url
  end

  def delete(url)
    @urls.delete(url)
  end

  def uniq
    @urls.uniq
  end

=begin
     validates_presence_of :trig_type
     validates_presence_of :address
     validates_uniqueness_of :address, scope: :trig_type
     validate :trig_type_is_valid

     def trig_type_is_valid
       "change" == :trig_type || "shelve" == :trig_type || "form" == :trig_type
     end
=end
 end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :create_remember_token

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/static_pages_controller.rb
require 'util_functions'

class StaticPagesController < ApplicationController
  before_filter :signed_in_user, only: [:webhooks]

  def home
  end

  def webhooks
    #@change = Utils::get_webhook_urls('webhook-change-commit')
    puts 'TTESTSTSTSTSTST'
    @change = Url.new('webhook-change-commit')
    puts 'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ'
    puts @change
    puts 'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ'
    @shelve = Url.new('webhook-shelve-commit')
    @form   = Url.new('webhook-form-commit')
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def create
    @urls = Url.new(params[:url][:trig_type])
    button = params[:url][:button_type]
    address = params[:url][:address]

    if ('add' == button && !(address.empty?))
      @urls << (address)
    elsif ('delete' == button)
      @urls.delete(address)
    end
    
    Utils::send_webhook_urls(params[:url][:trig_type], @urls.uniq)
    redirect_to webhooks_url    
  end


  private
     def url_params
       params.require(:url).permit(:urls, :address)
     end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'util_functions'

  def new
    @user = User.new
  end
  
  def create
    p4     = Utils::get_p4
    server = Utils::get_server

    #p4       = '/usr/local/bin/p4'
    #server   = '10.0.102.53:1209'
    user     = params[:user][:name]
    password = params[:user][:password]

    output = `/bin/echo #{password} | #{p4} -p #{server} -u #{user} login -p`
    #puts output
    regex = /\AEnter password: .?[A-Z0-9]+.?\z/m
    if output =~ regex
      @user = User.new(name: user)
      if @user.save
        sign_in @user
        redirect_to webhooks_path
      else
        @user = User.new
        render :new
      end
    else
      @user = User.new
      render :new
    end
  end

  def destroy
    @user = current_user
    puts 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    puts @user
    puts 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    sign_out
    @user.delete
    redirect_to signin_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
	    <li>
                  <%= link_to "Sign out", signout_path, method: :delete %>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/.#_url.html.erb
jbrower@dhcp-53-n102.dhcp.perforce.com.454

app/views/static_pages/_url.html.erb
<li class="list-group-item">
  <span class="address"><%= url %></span>
  <div>
    <%= form_for(:url, url: urls_path, html: {class: 'form-inline'}) do |f| %>
    <fieldset>
      <div class="input-group">
        <%= f.hidden_field :address,     :value => url     %>
        <%= f.hidden_field :trig_type,   :value => trig_type %>
        <%= f.hidden_field :button_type, :value => 'delete' %>
        <span class="input-group-btn">
          <%= f.submit "delete", class: "btn btn-link btn-del btn-xs" %>
        </span>
      </div><!-- /input-group -->
      </fieldset>
    <% end %>
  </div>
</li>

app/views/static_pages/_urlregion.html.erb
<div class="scrolling-region">
  <ul class="list-group">
    <% list.each do |element| %>
      <%= render partial: "url", locals: { trig_type: trigger, url: element } %>
    <% end %>
  </ul>
</div>

<%= form_for(:url, url: urls_path, html: {class: 'form-search'}) do |f| %>
  <div class="input-group">
    <%= f.text_field :address, placeholder: "URL" %>
    <%= f.hidden_field :trig_type, :value => trigger %>
    <%= f.hidden_field :button_type, :value => 'add' %>
    <span class="input-group-btn">
      <%= f.submit "Add", class: "btn btn-xs btn-primary" %>
    </span>
  </div><!-- /input-group -->
<% end %>

app/views/static_pages/webhooks.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <p>change-commit</p>
      <%= render partial: "urlregion",
	  locals: { list: @change, trigger: "webhook-change-commit" } %>
    </div>
    <div class="col-xs-4">
      <p>shelve-commit</p>
      <%= render partial: "urlregion",
	  locals: { list: @shelve, trigger: "webhook-shelve-commit" } %>
    </div>
    <div class="col-xs-4">
      <p>form-commit</p>
      <%= render partial: "urlregion",
	  locals: { list: @form, trigger: "webhook-form-commit" } %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign in</h1>

<div class="row">
  <div class="centered">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Login", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>